In [1]:
import numpy as np

**Creating Numpy Arrays**

In [4]:
arr1 = np.array([1, 2, 3, 4])   # 1D array
arr2 = np.array([ [1, 2, 3], [4, 5, 6] ])  # 2D array

print(arr1)
print(arr2)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


**Using: np.arange(), np.linspace(), np.zeros(), np.ones(), np.eye()**

In [6]:
arr = np.arange(1, 10, 2)   # [1, 3, 5, 7, 9]
arr_linspace = np.linspace(0, 1, 5)  # [0. 0.25 0.5 0.75 1.]
zeros = np.zeros((2, 3))          # [[0. 0. 0.] [0. 0. 0.]]  -- 2x3 matrix filled with 0s
ones = np.ones((3, 3))            # [[1. 1. 1.] [1. 1. 1.]] -- 3x3 matrix filled with 1s
identity_matrix = np.eye(3)       # [[1. 0. 0.] [0. 1. 0.] [0. 0. 1.]] -- 3x3 identity matrix

print(arr, arr_linspace, zeros, ones, identity_matrix)

[1 3 5 7 9] [0.   0.25 0.5  0.75 1.  ] [[0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Shape, Size, and Dimensionality of Arrays**

Checking Properties of an Array

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)  # (2, 3)
print(arr.size)   # 6
print(arr.ndim)   # 2
print(arr.dtype)  # int64 (or int32 depends on system)

(2, 3)
6
2
int64


**Indexing and Slicing**

Basic indexing

In [8]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])   # 10
print(arr[-1])  # 50

10
50


2D Indexing

In [12]:
arr2D = np.array([ [1, 2, 3], [4, 5, 6] ])
print(arr2D[0, 1])     # 2 (Row 0, Column 1)
print(arr2D[:, 1])     # [2 5]  (All rows, Column 1)

2
[2 5]


Slicing

In [13]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])      # [20 30 40]
print(arr[::-1])     # [50 40 30 20 10]

[20 30 40]
[50 40 30 20 10]


**Broadcasting and Vectorized Operations**

Element-wise Operations

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(a ** 2)

[5 7 9]
[ 4 10 18]
[1 4 9]


Broadcasting Example

In [17]:
A = np.array([[1], [2], [3]])   # Shape(3, 1)
B = np.array([4, 5, 6])         # Shape(1, 3)

print(A + B)
# output
# [[5 6 7]
#  [6 7 8]
#  [7 8 9]]

[[5 6 7]
 [6 7 8]
 [7 8 9]]


**Mathematical Functions**

In [20]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))     # 15
print(np.mean(arr))    # 3.0
print(np.std(arr))     # 1.4142 (Standard deviation or std)
print(np.max(arr))     # 5
print(np.min(arr))     # 1

15
3.0
1.4142135623730951
5
1


**Linear Algebra Operations**

Matrix Multiplication (np.dot())

In [3]:
A = np.array([ [1, 2], [3, 4] ])
B = np.array([ [5, 6], [7, 8] ])

print(np.dot(A, B))
# output
# [[19 22]
# [43 50]]

[[19 22]
 [43 50]]


Matrix Inversion

In [5]:
A = np.array([ [1, 2], [3, 4] ])
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


Eigenvalues and Eigenvectors

In [8]:
vals, vecs = np.linalg.eig(A)
print('Eigenvalues:', vals)
print('Eigenvectors:\n', vecs)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


**Random Number Generation**

In [10]:
rand_num = np.random.rand(3)                     # 3 random numbers between 0 and 1
rand_ints = np.random.randint(1, 10, (2, 2))     # 2x2 matrix with random integers

print(rand_num, rand_ints)

[0.94956703 0.52932682 0.81458025] [[1 9]
 [5 5]]


**Handling Missing Values**

In [11]:
arr = np.array([1, 2, np.nan, 4])
print(np.nanmean(arr))     # Ignores NaN while calculating mean

2.3333333333333335


**Performance Optimization**

In [12]:
import time

arr = np.random.rand(1000000)

start = time.time()
sum1 = np.sum(arr)      # Fast Numpy operation
end = time.time()
print('Numpy sum:', end - start)

Numpy sum: 0.0011301040649414062


**Memory Layout and Strides**

In [16]:
 # Memory step size in bytes
arr1 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
arr2 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)
print(arr1.strides)
print(arr2.strides)

(12, 4)
(24, 8)
