In [ ]:
import numpy as np

**Creating Numpy Arrays**

In [ ]:
arr1 = np.array([1, 2, 3, 4])   # 1D array
arr2 = np.array([ [1, 2, 3], [4, 5, 6] ])  # 2D array

print(arr1)
print(arr2)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


**Using: np.arange(), np.linspace(), np.zeros(), np.ones(), np.eye()**

In [ ]:
arr = np.arange(1, 10, 2)   # [1, 3, 5, 7, 9]
arr_linspace = np.linspace(0, 1, 5)  # [0. 0.25 0.5 0.75 1.]
zeros = np.zeros((2, 3))          # [[0. 0. 0.] [0. 0. 0.]]  -- 2x3 matrix filled with 0s
ones = np.ones((3, 3))            # [[1. 1. 1.] [1. 1. 1.]] -- 3x3 matrix filled with 1s
identity_matrix = np.eye(3)       # [[1. 0. 0.] [0. 1. 0.] [0. 0. 1.]] -- 3x3 identity matrix

print(arr, arr_linspace, zeros, ones, identity_matrix)

[1 3 5 7 9] [0.   0.25 0.5  0.75 1.  ] [[0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Shape, Size, and Dimensionality of Arrays**

In [ ]:
# Checking Properties of an Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)  # (2, 3)
print(arr.size)   # 6
print(arr.ndim)   # 2
print(arr.dtype)  # int64 (or int32 depends on system)

(2, 3)
6
2
int64


**Indexing and Slicing**